# medisecure-backend/docker-compose.yml
services:
  # Base de données PostgreSQL
  medisecure-db:
    image: postgres:15-alpine
    container_name: medisecure-db
    environment:
      POSTGRES_DB: medisecure
      POSTGRES_USER: medisecure_user
      POSTGRES_PASSWORD: medisecure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medisecure_user -d medisecure"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API FastAPI
  medisecure-api:
    build:
      context: ./medisecure-backend/
    container_name: medisecure-api
    environment:
      DATABASE_URL: postgresql://medisecure_user:medisecure_password@medisecure-db:5432/medisecure
      SECRET_KEY: your-secret-key-here-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      medisecure-db:
        condition: service_healthy
    volumes:
      - ./medisecure-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend React
  medisecure-frontend:
    build:
      context: ./medisecure-frontend/
    container_name: medisecure-frontend
    ports:
      - "3001:3000"
    depends_on:
      - medisecure-api
    volumes:
      - ./medisecure-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  # PgAdmin (optionnel, pour la gestion de la base de données)
  medisecure-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: medisecure-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@medisecure.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - medisecure-db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: